# Generated by Django 4.2.3 on 2024-02-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_total_l_0bcd7e_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='total_likes',
        ),
    ]
